// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: trip.proto

package trippb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TripServicesClient is the client API for TripServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServicesClient interface {
	GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*GetTripResponse, error)
}

type tripServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServicesClient(cc grpc.ClientConnInterface) TripServicesClient {
	return &tripServicesClient{cc}
}

func (c *tripServicesClient) GetTrip(ctx context.Context, in *GetTripRequest, opts ...grpc.CallOption) (*GetTripResponse, error) {
	out := new(GetTripResponse)
	err := c.cc.Invoke(ctx, "/coolcar.TripServices/GetTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServicesServer is the server API for TripServices service.
// All implementations must embed UnimplementedTripServicesServer
// for forward compatibility
type TripServicesServer interface {
	GetTrip(context.Context, *GetTripRequest) (*GetTripResponse, error)
	mustEmbedUnimplementedTripServicesServer()
}

// UnimplementedTripServicesServer must be embedded to have forward compatible implementations.
type UnimplementedTripServicesServer struct {
}

func (UnimplementedTripServicesServer) GetTrip(context.Context, *GetTripRequest) (*GetTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrip not implemented")
}
func (UnimplementedTripServicesServer) mustEmbedUnimplementedTripServicesServer() {}

// UnsafeTripServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServicesServer will
// result in compilation errors.
type UnsafeTripServicesServer interface {
	mustEmbedUnimplementedTripServicesServer()
}

func RegisterTripServicesServer(s grpc.ServiceRegistrar, srv TripServicesServer) {
	s.RegisterService(&TripServices_ServiceDesc, srv)
}

func _TripServices_GetTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServicesServer).GetTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coolcar.TripServices/GetTrip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServicesServer).GetTrip(ctx, req.(*GetTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TripServices_ServiceDesc is the grpc.ServiceDesc for TripServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coolcar.TripServices",
	HandlerType: (*TripServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrip",
			Handler:    _TripServices_GetTrip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip.proto",
}
